### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ericnyamu** [nadams810/yaig#1]
Hi.here's my situation.i have some computers that are behind a nat.i would like to pass this 'natting ip' through a vpn,so that all the pc behind the nat can be using the vpn.how should the iptables commands look like.The vpn interface is tun0 and the natting interface is eth0.thanks

**Comment by nadams810** [comment]
I would normally answer this type of unrelated question but the author has spammed it across several different projects.

I'm closing this as wontfix.

**Comment by ericnyamu** [comment]
oh. come OOOOOON.booooo.boring.stop feeling so special.i can ask as many people as i want.you arenot the only answer.and its an iptables related question
